words = [
    "DEFVAL",
    "DEFVALA",
    "DEFVALB",
    "GPINTEN",
    "GPINTENA",
    "GPINTENB",
    "GPIOB",
    "GPPUA",
    "GPPUB",
    "HAEN",
    "INTCAPA",
    "INTCAPB",
    "INTCON",
    "INTCONA",
    "INTCONB",
    "INTFA",
    "INTFB",
    "INTPOL",
    "IOCON",
    "IODIR",
    "IODIRA",
    "IODIRB",
    "IPOLA",
    "IPOLB",
    "MCP",
    "OLATA",
    "POR",
    "PORTB",
    "RPPAL",
    "gpioa",
    "mockspi",
]
